[tools]
java = { version = "openjdk-21" }
bun = "latest"
python = "3.14.0"
zig = "0.15.2"

# golang
go = "latest"
golangci-lint = "latest"
gofumpt = "latest"

# mongodb
mongodb = "8.1.2"
mongosh = "latest"
